
export const UPDATE_USER_INFO = 'user/UPDATE_USER_INFO';

export const ON_CREATE_PROJECT_DIALOG = 'user/ON_CREATE_PROJECT_DIALOG';
export const UPDATE_CREATE_PROJECT_DIALOG = 'user/UPDATE_CREATE_PROJECT_DIALOG';

export const CREATE_PROJECT_REQUEST = 'user/CREATE_PROJECT';
