
export const UPDATE_USER_INFO = 'user/UPDATE_USER_INFO';

export const ON_CREATE_PROJECT_DIALOG = 'user/ON_CREATE_PROJECT_DIALOG';
export const UPDATE_CREATE_PROJECT_DIALOG = 'user/UPDATE_CREATE_PROJECT_DIALOG';

export const CREATE_PROJECT_REQUEST = 'user/CREATE_PROJECT';

export const UPDATE_USER_PROJECTS = 'user/UPDATE_USER_PROJECTS';

export const ON_PAGE_LOAD = 'user/ON_PAGE_LOAD';

export const UPDATE_ADD_AMOUNT_DIALOG = 'user/UPDATE_ADD_AMOUNT_DIALOG';

export const OPEN_ADD_AMOUNT_DIALOG = 'user/OPEN_ADD_AMOUNT_DIALOG';

export const ADD_AMOUNT = 'user/ADD_AMOUNT';
